In [3]:
pip install tensorflow opencv-python numpy matplotlib tensorflow-hub


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import os
import cv2
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
import time

# Load the pre-trained SSD model from TensorFlow Hub
detector = hub.load("https://tfhub.dev/tensorflow/ssd_mobilenet_v2/2")

def preprocess_image(img_path):
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    return img

def detect_objects(image):
    img = tf.convert_to_tensor(image, dtype=tf.uint8)[tf.newaxis, ...]
    result = detector(img)
    return result

def calculate_distance(detection, image_shape):
    # Debug: Print the detection boxes
    print("Detection boxes:", detection['detection_boxes'][0].numpy())
    bbox = detection['detection_boxes'][0][0].numpy()  # Get the first detection
    ymin, xmin, ymax, xmax = bbox
    width = xmax - xmin
    height = ymax - ymin
    distance = 1 / (width * height)  # Simplified example
    return distance

def estimate_speed(previous_distance, current_distance, time_elapsed):
    speed = (current_distance - previous_distance) / time_elapsed
    return speed

def calculate_ttc(distance, speed):
    if speed <= 0:
        return float('inf')
    ttc = distance / speed
    return ttc

def issue_warning(ttc):
    if ttc < 0.7:
        print(f"Warning: Collision imminent in {ttc:.2f} seconds!")
    else:
        print("Safe")

# Path to your image
img_path = r'C:\Users\sai\Desktop\intel project eureka\vechile_cut-in_detection_system\car data set\images\0001308.jpeg'

# Load and preprocess the image
preprocessed_image = preprocess_image(img_path)

# Detect objects
detections = detect_objects(preprocessed_image)

# Calculate distance
distance = calculate_distance(detections, preprocessed_image.shape)
print(f"Estimated distance: {distance}")

# Simulate previous distance and time elapsed for speed estimation
previous_distance = 10  # Placeholder value
time_elapsed = 1        # Placeholder value

# Estimate speed
speed = estimate_speed(previous_distance, distance, time_elapsed)
print(f"Estimated speed: {speed}")

# Calculate Time to Collision (TTC)
ttc = calculate_ttc(distance, speed)
print(f"Estimated Time to Collision: {ttc}")

# Issue warning if necessary
issue_warning(ttc)


Detection boxes: [[0.00578856 0.56253755 0.9870952  1.        ]
 [0.46187386 0.18067136 0.516569   0.21461749]
 [0.53209513 0.         0.9787032  0.09037198]
 [0.4603808  0.37841654 0.7736149  0.55379367]
 [0.35666054 0.14522068 0.7766333  0.3393432 ]
 [0.4603808  0.37841654 0.7736149  0.55379367]
 [0.3545949  0.14289975 0.7741658  0.33746326]
 [0.4603808  0.37841654 0.7736149  0.55379367]
 [0.55822855 0.33013725 0.87216944 0.4136033 ]
 [0.5016108  0.36782694 0.6108956  0.40444452]
 [0.71842676 0.3017932  0.9689885  0.40335342]
 [0.4573112  0.18380697 0.49200654 0.20514776]
 [0.5060638  0.42894638 0.59198475 0.478962  ]
 [0.35003218 0.15236376 0.7730433  0.52407587]
 [0.5167705  0.49770662 0.5788516  0.5218088 ]
 [0.3545949  0.14289975 0.7741658  0.33746326]
 [0.44439006 0.39896858 0.7949424  0.54648906]
 [0.47844365 0.37811658 0.52808315 0.40924683]
 [0.5206241  0.00737036 0.6031832  0.04236534]
 [0.4608751  0.39776382 0.7710554  0.5421057 ]
 [0.49978077 0.00980896 0.8873911  0.124093